import XCTest
import simd
@testable import CTModels

/// The strongest available check on `SceneryModelPlacement.worldTransform`'s
/// rotation formula, and the one this whole saga was missing: an
/// *independent, from-scratch* re-implementation of the reference tool's
/// actual algorithm (`SMViewer.cs`/`RMViewer.cs`'s `LoadSceneryModel`,
/// transcribed instruction-for-instruction below, including its own
/// `Vector4 * Matrix4` row-vector semantics — verified against OpenTK's own
/// `Transform(ref Vector4, ref Matrix4, out Vector4)` source, not assumed),
/// run on concrete numeric input and compared directly against
/// `worldTransform`'s output for the *same* input. Every previous version
/// of this formula was checked either by hand-tracing the reference
/// source's arithmetic (which doesn't resolve a row/column-vector
/// convention ambiguity) or by real-data geometric alignment (which is
/// blind to a uniform sign/handedness flip — a rotation matrix R and its
/// transpose R^T produce identical *relative* alignment between two
/// placements that share the same error). This test sidesteps both blind
/// spots: it doesn't assume anything about which convention is "correct,"
/// it mechanically runs the reference algorithm's own steps on literal
/// numbers and checks the two implementations agree on where a real vertex
/// ends up, vertex-for-vertex.
final class SceneryReferenceAlgorithmCrossCheckTests: XCTestCase {
    /// A direct line-for-line port of `LoadSceneryModel`'s matrix
    /// construction (`SMViewer.cs`/`RMViewer.cs`), including the row0
    /// per-component negation and the `Matrix4.CreateScale(-1,1,1)`
    /// post-multiply, followed by the exact row-vector vertex transform
    /// (`vertexPos *= modelMatrix`, i.e. OpenTK's `Vector4 operator*(Vector4
    /// vec, Matrix4 mat)` -> `Transform(ref vec, ref mat, out result)`:
    /// `result[j] = sum_i vec[i] * mat.Row_i[j]`). Deliberately does not
    /// call or share any code with `SceneryModelPlacement.worldTransform` —
    /// an independent implementation is the entire point.
    private func referenceToolWorldVertex(row0: SIMD4<Float>, row1: SIMD4<Float>, row2: SIMD4<Float>, row3: SIMD4<Float>, local: SIMD3<Float>) -> SIMD3<Float> {
        // Step 1: build modelMatrix's 4 rows exactly as LoadSceneryModel does.
        var m0 = SIMD4<Float>(-row0.x, row1.x, row2.x, row0.w)
        var m1 = SIMD4<Float>(-row0.y, row1.y, row2.y, row1.w)
        var m2 = SIMD4<Float>(-row0.z, row1.z, row2.z, row2.w)
        var m3 = SIMD4<Float>(row3.x, row3.y, row3.z, row3.w)

        // Step 2: modelMatrix *= Matrix4.CreateScale(-1, 1, 1) -- standard
        // matrix multiply by a diagonal matrix negates column 0 of the
        // left-hand matrix (verified against Matrix4.Mult's own row-by-
        // column-dot-product source, not assumed as a shortcut).
        m0.x = -m0.x
        m1.x = -m1.x
        m2.x = -m2.x
        m3.x = -m3.x

        // Step 3: vertexPos = Vector4(local, 1) * modelMatrix -- row-vector
        // multiply: result[j] = sum_i vec[i] * mat.Row_i[j].
        let vec = SIMD4<Float>(local.x, local.y, local.z, 1)
        let rows = [m0, m1, m2, m3]
        var result = SIMD3<Float>(0, 0, 0)
        result.x = vec.x * rows[0].x + vec.y * rows[1].x + vec.z * rows[2].x + vec.w * rows[3].x
        result.y = vec.x * rows[0].y + vec.y * rows[1].y + vec.z * rows[2].y + vec.w * rows[3].y
        result.z = vec.x * rows[0].z + vec.y * rows[1].z + vec.z * rows[2].z + vec.w * rows[3].z
        return result
    }

    private func worldTransformVertex(row0: SIMD4<Float>, row1: SIMD4<Float>, row2: SIMD4<Float>, row3: SIMD4<Float>, local: SIMD3<Float>) -> SIMD3<Float> {
        let placement = SceneryModelPlacement(modelID: 1, isSpecial: false, boundingBoxMin: .zero, boundingBoxMax: .zero, modelMatrix: [row0, row1, row2, row3])
        guard let transform = placement.worldTransform else {
            XCTFail("expected a valid worldTransform")
            return .zero
        }
        return transform.rotation.act(local * transform.scale) + transform.position
    }

    /// A genuine compound rotation (40° about a tilted, non-axis-aligned
    /// direction) with non-uniform scale -- real, valid on-disk rows
    /// (mutually orthogonal before scaling, exactly what an actual rotate
    /// + non-uniform-scale placement matrix looks like), computed
    /// independently in Python from a target rotation/scale via
    /// `row_i[j] = scale_j * rotationMatrix[i][j]` and hand-copied in as
    /// literals -- not generated by any code in this codebase, so there's
    /// no risk of this test accidentally sharing a formula with either
    /// implementation under test. Deliberately compound (not a single-axis
    /// rotation like the 90°-about-Y case below) so a row/column mixup or
    /// axis-specific sign error can't coincidentally cancel out.
    func testWorldTransformMatchesTheReferenceAlgorithmForArbitraryAsymmetricInput() {
        let row0 = SIMD4<Float>(1.5693561, -0.1764739, 0.9256592, 0)
        let row1 = SIMD4<Float>(0.3660977, 2.9192543, -0.2099956, 0)
        let row2 = SIMD4<Float>(-1.1845226, 0.6684395, 1.1614891, 0)
        let row3 = SIMD4<Float>(10, 11, 12, 1)

        for local in [SIMD3<Float>(1, 0, 0), SIMD3<Float>(0, 1, 0), SIMD3<Float>(0, 0, 1), SIMD3<Float>(1, 1, 1)] {
            let reference = referenceToolWorldVertex(row0: row0, row1: row1, row2: row2, row3: row3, local: local)
            let ours = worldTransformVertex(row0: row0, row1: row1, row2: row2, row3: row3, local: local)
            XCTAssertLessThan(simd_distance(reference, ours), 0.01, "local \(local): reference tool gives \(reference), worldTransform gives \(ours)")
        }
    }

    /// A real 90°-about-Y-like on-disk matrix (the exact shape a rotated
    /// floor tile would have), to directly settle "should Rotation Y read
    /// +90 or -90" against the reference algorithm's own output, not
    /// against intuition about which one "sounds right."
    func testWorldTransformMatchesTheReferenceAlgorithmForANinetyDegreeYLikeMatrix() {
        // A matrix whose on-disk rows are NOT already the "nice" values
        // worldTransform's own hand-derived unit tests use -- constructed
        // independently here (real PS2 rotation matrices are rarely exact
        // integers) to avoid any risk of accidentally testing the same
        // formula against itself.
        let row0 = SIMD4<Float>(0.0, 0.0, 2.5, 0)
        let row1 = SIMD4<Float>(0.0, 2.5, 0.0, 0)
        let row2 = SIMD4<Float>(-2.5, 0.0, 0.0, 0)
        let row3 = SIMD4<Float>(3, 4, 5, 1)

        for local in [SIMD3<Float>(1, 0, 0), SIMD3<Float>(0, 0, 1)] {
            let reference = referenceToolWorldVertex(row0: row0, row1: row1, row2: row2, row3: row3, local: local)
            let ours = worldTransformVertex(row0: row0, row1: row1, row2: row2, row3: row3, local: local)
            XCTAssertLessThan(simd_distance(reference, ours), 0.01, "local \(local): reference tool gives \(reference), worldTransform gives \(ours)")
        }
    }
}
