import SwiftUI
import CTModels
import CTParsers
import simd

/// Write-back editor for a decoded `ColData` record — ports the
/// `ColDataEditor`'s trigger-tree visualization as an editable list of
/// the underlying trigger boxes, since the reference editor itself only
/// surfaces the tree (no per-trigger fields). The triangles/vertices/
/// groups sections of the on-disk blob are shown read-only: editing
/// individual vertex/triangle bytes is meaningless (any change would
/// silently break the surface-index math), so the only safe edit is the
/// trigger box set, which the writer re-emits verbatim.
///
/// "Parity Phase I": also ports `Workers/CollisionImporter.cs` — importing
/// one or more Wavefront `.obj` files, each assigned its own surface ID,
/// replaces this record's *entire* mesh (vertices/triangles/groups/
/// triggers all regenerated by `CollisionOBJImporter`) rather than editing
/// individual fields, so it saves via a whole-record replace
/// (`WorkspaceViewModel.patchedFileBytes(replacingWholeRecord:with:)`,
/// same path Phase B/D/E established), not the trigger-only same-size
/// patch the rest of this sheet uses.
struct ColDataEditorSheet: View {
    @Environment(WorkspaceViewModel.self) private var workspace
    @Environment(\.dismiss) private var dismiss
    let node: ChunkNode
    let original: CollisionMesh

    @State private var triggerBoxes: [CollisionTriggerBox]
    @State private var errorMessage: String?
    @State private var isSaving = false

    @State private var stagedModels: [StagedOBJModel] = []
    @State private var maxPolysPerGroup: Double = 32
    @State private var importError: String?
    @State private var isGenerating = false

    private struct StagedOBJModel: Identifiable {
        let id = UUID()
        var fileName: String
        var model: CollisionOBJImporter.ParsedOBJModel
        var surfaceID: Int
    }

    init(node: ChunkNode, mesh: CollisionMesh) {
        self.node = node
        self.original = mesh
        _triggerBoxes = State(initialValue: mesh.triggerBoxes)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Edit ColData #\(original.id)").font(.title3.bold())
            Text("Triggers are editable. Vertices, triangles, and groups are read-only; editing them would silently corrupt the surface-ID math. Importing an OBJ mesh below replaces all of it at once instead.")
                .font(.caption2)
                .foregroundStyle(.secondary)

            Form {
                Section("Triggers (\(triggerBoxes.count))") {
                    ForEach(triggerBoxes.indices, id: \.self) { i in
                        TriggerBoxFields(box: $triggerBoxes[i])
                    }
                }
                importSection
            }
            .formStyle(.grouped)

            if let errorMessage {
                Label(errorMessage, systemImage: "exclamationmark.triangle")
                    .font(.caption2)
                    .foregroundStyle(.orange)
            }

            HStack {
                Spacer()
                Button("Cancel") { dismiss() }
                Button(isSaving ? "Saving…" : "Save Edited Copy…") { save() }
                    .keyboardShortcut(.defaultAction)
                    .disabled(isSaving)
            }
        }
        .padding()
        .frame(minWidth: 560, minHeight: 560)
    }

    private var importSection: some View {
        Section("Import Collision Mesh from OBJ") {
            Stepper("Max Polys Per Group: \(Int(maxPolysPerGroup))", value: $maxPolysPerGroup, in: 1...4096)
            Text("Applied when a file is added below. Changing this afterward doesn't retroactively regroup already-staged files, matching the reference tool's own behavior.")
                .font(.caption2)
                .foregroundStyle(.secondary)
            Button("Add OBJ File(s)…") { presentAddOBJPanel() }

            ForEach(stagedModels) { staged in
                HStack {
                    VStack(alignment: .leading, spacing: 1) {
                        Text(staged.fileName).lineLimit(1)
                        Text("\(staged.model.vertexCount) vert(s), \(staged.model.triangleCount) tri(s), \(staged.model.groups.count) group(s)")
                            .font(.caption2)
                            .foregroundStyle(.secondary)
                    }
                    Spacer()
                    Text("Surface").font(.caption2)
                    TextField("", text: Binding(
                        get: { "\(staged.surfaceID)" },
                        set: { text in
                            guard let value = Int(text), let i = stagedModels.firstIndex(where: { $0.id == staged.id }) else { return }
                            stagedModels[i].surfaceID = value
                        }
                    ))
                    .textFieldStyle(.roundedBorder)
                    .frame(width: 50)
                    Button(role: .destructive) {
                        stagedModels.removeAll { $0.id == staged.id }
                    } label: {
                        Image(systemName: "minus.circle")
                    }
                    .buttonStyle(.borderless)
                }
            }

            if !stagedModels.isEmpty {
                let totalVerts = stagedModels.reduce(0) { $0 + $1.model.vertexCount }
                let totalTris = stagedModels.reduce(0) { $0 + $1.model.triangleCount }
                let totalGroups = stagedModels.reduce(0) { $0 + $1.model.groups.count }
                Text("Total: \(totalVerts) vertices, \(totalTris) triangles, \(totalGroups) groups, \(totalGroups * 2 - 1) triggers")
                    .font(.caption2)
                    .foregroundStyle(.secondary)
                Button(isGenerating ? "Generating…" : "Generate & Replace Mesh…") { generateAndSave() }
                    .disabled(isGenerating)
            }
            if let importError {
                Label(importError, systemImage: "exclamationmark.triangle")
                    .font(.caption2)
                    .foregroundStyle(.orange)
            }
        }
    }

    private func presentAddOBJPanel() {
        let panel = NSOpenPanel()
        panel.allowsMultipleSelection = true
        panel.canChooseDirectories = false
        panel.canChooseFiles = true
        panel.allowedContentTypes = [.init(filenameExtension: "obj") ?? .item]
        panel.message = "Choose one or more Wavefront .obj files to import as this level's collision mesh. Each file becomes its own group of triangles with one assigned surface ID."
        guard panel.runModal() == .OK else { return }

        importError = nil
        let maxPolys = Int(maxPolysPerGroup)
        for url in panel.urls {
            do {
                let text = try String(contentsOf: url, encoding: .utf8)
                let parsed = CollisionOBJImporter.parseOBJ(text, maxPolysPerGroup: maxPolys)
                guard !parsed.groups.isEmpty else { continue }
                stagedModels.append(StagedOBJModel(fileName: url.lastPathComponent, model: parsed, surfaceID: 0))
            } catch {
                importError = "Couldn't read \(url.lastPathComponent): \(error.localizedDescription)"
            }
        }
    }

    private func generateAndSave() {
        importError = nil
        let mesh = CollisionOBJImporter.buildCombinedMesh(
            id: original.id,
            models: stagedModels.map { (model: $0.model, surfaceID: $0.surfaceID) }
        )
        let encoded = ColDataWriter.write(mesh)
        guard let patchedBytes = workspace.patchedFileBytes(replacingWholeRecord: node, with: encoded) else { return }
        guard let url = ExportPanel.chooseSaveLocation(
            suggestedName: "\(node.displayName)_edited.rm2",
            message: "Save the edited copy of this file, with this ColData's whole mesh replaced by the imported OBJ geometry. The original file on disk is not modified."
        ) else { return }
        isGenerating = true
        Task {
            do {
                try await workspace.writeDataAsync(patchedBytes, to: url)
                workspace.statusMessage = "Saved edited copy to \(url.lastPathComponent) with this ColData's mesh replaced by the imported OBJ geometry."
                isGenerating = false
                dismiss()
            } catch {
                workspace.lastError = "Save failed: \(error)"
                isGenerating = false
            }
        }
    }

    private func save() {
        errorMessage = nil
        var edited = original
        edited.triggerBoxes = triggerBoxes

        let encoded = ColDataWriter.write(edited)
        guard let patchedBytes = workspace.patchedFileBytes(replacing: node, with: encoded) else { return }
        guard let url = ExportPanel.chooseSaveLocation(
            suggestedName: "\(node.displayName)_edited.rm2",
            message: "Save the edited copy of this file, with this ColData changed. The original file on disk is not modified."
        ) else { return }
        isSaving = true
        Task {
            do {
                try await workspace.writeDataAsync(patchedBytes, to: url)
                workspace.statusMessage = "Saved edited copy to \(url.lastPathComponent) with this ColData changed. The original file was not modified."
                isSaving = false
                dismiss()
            } catch {
                workspace.lastError = "Save failed: \(error)"
                isSaving = false
            }
        }
    }
}

private struct TriggerBoxFields: View {
    @Binding var box: CollisionTriggerBox

    var body: some View {
        DisclosureGroup("Trigger \(box.flag1) → \(box.flag2)") {
            VStack(alignment: .leading) {
                FloatField("Min X", value: Binding(get: { Double(box.min.x) }, set: { box.min.x = Float($0) }))
                FloatField("Min Y", value: Binding(get: { Double(box.min.y) }, set: { box.min.y = Float($0) }))
                FloatField("Min Z", value: Binding(get: { Double(box.min.z) }, set: { box.min.z = Float($0) }))
                FloatField("Max X", value: Binding(get: { Double(box.max.x) }, set: { box.max.x = Float($0) }))
                FloatField("Max Y", value: Binding(get: { Double(box.max.y) }, set: { box.max.y = Float($0) }))
                FloatField("Max Z", value: Binding(get: { Double(box.max.z) }, set: { box.max.z = Float($0) }))
                LabeledContent("Flag 1") { TextField("value", text: Binding(get: { "\(box.flag1)" }, set: { box.flag1 = Int32($0) ?? box.flag1 })).textFieldStyle(.roundedBorder) }
                LabeledContent("Flag 2") { TextField("value", text: Binding(get: { "\(box.flag2)" }, set: { box.flag2 = Int32($0) ?? box.flag2 })).textFieldStyle(.roundedBorder) }
            }
        }
    }
}

private struct FloatField: View {
    let label: String
    @Binding var value: Double
    @State private var text: String = ""

    init(_ label: String, value: Binding<Double>) {
        self.label = label
        self._value = value
    }

    var body: some View {
        LabeledContent(label) {
            TextField("value", text: $text)
                .textFieldStyle(.roundedBorder)
                .onAppear { text = Self.format(value) }
                .onChange(of: value) { _, newValue in text = Self.format(newValue) }
                .onChange(of: text) { _, _ in commit() }
                .onSubmit { commit() }
        }
    }

    private func commit() {
        if let parsed = Double(text) { value = parsed }
    }

    private static func format(_ v: Double) -> String {
        v.truncatingRemainder(dividingBy: 1) == 0 ? String(Int64(v)) : "\(v)"
    }
}
