import Foundation

public enum CrateExportError: Error, LocalizedError {
    case zipToolUnavailable
    case zipFailed(Int32)

    public var errorDescription: String? {
        switch self {
        case .zipToolUnavailable: return "The system zip tool (/usr/bin/zip) isn't available on this Mac."
        case .zipFailed(let code): return "zip exited with status \(code)."
        }
    }
}

public struct CrateMetadata: Sendable {
    public var name: String
    public var description: String
    public var author: String
    public var version: String
    public var targetGame: String

    public init(name: String, description: String, author: String, version: String, targetGame: String) {
        self.name = name
        self.description = description
        self.author = author
        self.version = version
        self.targetGame = targetGame
    }
}

/// "Crate Mod Loader & Multi-Game Packager (.Crate Export)" (blueprint 3.3):
/// packages files into a real CrateModLoader-compatible `.crate` archive —
/// verified against the actual loader source
/// (`CrateModLoader-master/CrateModAPI/ModCrates.cs`: `InfoFileName =
/// "modcrateinfo.txt"`, `LayerFolderName = "layer"`, `Separator = '='`,
/// `CommentSymbol = '!'`, and the `Prop_*` manifest keys), not guessed at
/// from the name alone. A `.crate` is a plain zip: a `modcrateinfo.txt`
/// key=value manifest at the root, plus one `layer<N>/` folder per install
/// layer that mirrors the target game's own folder structure with the
/// actual modded file(s) inside — `CrateModLoader.InstallLayerMod` extracts
/// each `layerN/...` entry straight onto the game's install directory at
/// the matching relative path.
public enum CrateExporter {
    /// `relativePath` on each file is placed under `layer0/` — this build
    /// has no verified in-game archive path for an edited `.RM2`/`.SM2`
    /// (that would mean knowing exactly where the original `.BD` expects it
    /// back, which isn't tracked yet), so callers pass just the file's own
    /// name and the resulting crate lands it at the mod's root; a user
    /// installing it can relocate it into the right in-game subfolder same
    /// as any other layer file.
    public static func export(files: [(relativePath: String, data: Data)], metadata: CrateMetadata, to crateURL: URL) throws {
        let stagingDir = FileManager.default.temporaryDirectory.appendingPathComponent("TwinsanityStudioCrate-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: stagingDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: stagingDir) }

        let infoLines = [
            "!Generated by Twinsanity Studio",
            "Name=\(sanitizedLine(metadata.name))",
            "Description=\(sanitizedLine(metadata.description))",
            "Author=\(sanitizedLine(metadata.author))",
            "Version=\(sanitizedLine(metadata.version))",
            "ModLoaderVersion=1.0",
            "Game=\(sanitizedLine(metadata.targetGame))"
        ]
        try (infoLines.joined(separator: "\n") + "\n")
            .write(to: stagingDir.appendingPathComponent("modcrateinfo.txt"), atomically: true, encoding: .utf8)

        let layerDir = stagingDir.appendingPathComponent("layer0")
        for file in files {
            let destination = layerDir.appendingPathComponent(file.relativePath)
            try FileManager.default.createDirectory(at: destination.deletingLastPathComponent(), withIntermediateDirectories: true)
            try file.data.write(to: destination)
        }

        if FileManager.default.fileExists(atPath: crateURL.path) {
            try FileManager.default.removeItem(at: crateURL)
        }
        try zip(contentsOf: stagingDir, to: crateURL)
    }

    /// `modcrateinfo.txt` is parsed line-by-line, splitting on the first
    /// `=` (`ModCrates.Separator`) — a value containing its own `=`/newline
    /// would desync that parse, so both get stripped rather than escaped
    /// (there's no escaping convention in the real format to escape into).
    private static func sanitizedLine(_ value: String) -> String {
        value.replacingOccurrences(of: "\n", with: " ").replacingOccurrences(of: "=", with: "-")
    }

    /// Shells out to the system `zip` (a standard BSD userland tool present
    /// on every macOS install, not a third-party dependency) rather than
    /// hand-rolling a zip writer or reaching for a framework that produces
    /// Apple's own `.aar` archive format — `CrateModLoader` reads crates
    /// with .NET's `System.IO.Compression.ZipFile`, which needs a real,
    /// standard zip container, not an Apple-specific one.
    private static func zip(contentsOf directory: URL, to destination: URL) throws {
        guard FileManager.default.fileExists(atPath: "/usr/bin/zip") else {
            throw CrateExportError.zipToolUnavailable
        }
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/zip")
        process.currentDirectoryURL = directory
        process.arguments = ["-r", "-X", destination.path, "."]
        process.standardOutput = Pipe()
        process.standardError = Pipe()
        try process.run()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            throw CrateExportError.zipFailed(process.terminationStatus)
        }
    }
}
