import Foundation

/// Real (de)serialization for CrateModLoader's `modcratesettings.txt` file —
/// the write-side counterpart to `ModManifest.settings`/`ModManifestParser`
/// (which already read it back, since `CrateArchiveManager.readManifest`
/// needed that for "Crate Region Gating"). Format verified against
/// `CrateModLoader-master/CrateModAPI/ModCrates.cs`:
/// - `SettingsFileName = "modcratesettings.txt"`, the shared `Separator =
///   '='`/`CommentSymbol = '!'` constants `modcrateinfo.txt` also uses.
/// - `ModCrates.LoadMetadata`'s settings-file read loop: skip any line
///   whose first character is `!`, otherwise split on `=` into a
///   `Settings[key] = value` pair — the exact same shape
///   `ModManifestParser.parseKeyValues` already implements.
/// - `ModCrates.SaveSettingsToFile`/`SaveSettingsToCrate`: one leading
///   `!`-prefixed generator comment line, then one `<CodeName>=<value>`
///   line per mod property, only including a property when `fullSettings
///   || prop.HasChanged` (`fullSettings: false` is CrateModLoader's own
///   "diff-only" save).
///
/// CrateModLoader's diff-only save is keyed off `ModPropertyBase.HasChanged`
/// — a live, mutable flag the Mod Menu UI sets to `true` the moment the
/// user actually edits a property (`ModPropertyBase.ValueChange`), and
/// which `ResetToDefault` explicitly clears back to `false`. It is *not* a
/// value-equality check performed at save time: a property nudged back to
/// its original value by hand still has `HasChanged == true` and would
/// still be written by a diff-only save. This app has no equivalent of
/// CrateModLoader's global "Mod Menu" property registry (`Modder.Props`,
/// each entry a live `ModPropertyBase`) to hang a real `HasChanged` flag
/// off of — this app's editing model is per-record-type inspectors, not a
/// single mod-property list. `diffFromDefaults` below is therefore a
/// simplification, not a port: a plain value-equality diff against a
/// caller-supplied defaults dictionary, honestly weaker than the real
/// tool's mutation tracking (it would omit a value the user deliberately
/// set back to its default, where the real tool would still include it),
/// but the closest honest analog available without a property registry to
/// port `HasChanged` from.
public enum ModCrateSettings {
    /// Serializes `settings` into the real `modcratesettings.txt` text
    /// format. The real generator's own leading comment reads `"! <version>
    /// Auto-Generated Settings File"` (`SaveSettingsToFile`) — the exact
    /// wording is free-form since the real reader only ever checks for the
    /// leading `!` (`ModCrates.LoadMetadata`'s `line[0] != CommentSymbol`
    /// check), so this reuses this app's own existing `modcrateinfo.txt`
    /// comment convention (`CrateExporter.export`'s `"!Generated by
    /// Twinsanity Studio"`) instead of literally reproducing the C#
    /// version string. Entries are written in sorted key order for a
    /// stable, diff-friendly file — the real tool emits them in
    /// `Modder.Props` declaration order, which this app has no equivalent
    /// ordered registry for.
    public static func serialize(_ settings: [String: String]) -> String {
        var lines = ["!Generated by Twinsanity Studio"]
        for key in settings.keys.sorted() {
            lines.append("\(sanitizedLine(key))=\(sanitizedLine(settings[key] ?? ""))")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Parses `modcratesettings.txt` text back into a `[String: String]`.
    /// This is genuinely the same key=value/`!`-comment format
    /// `ModManifestParser.parseKeyValues` already implements for exactly
    /// this file (see `ModManifest.settings`) — exposed again here under
    /// this file's own name so a caller working with settings text in
    /// isolation (e.g. these round-trip tests, or a future standalone
    /// settings-file load path mirroring the real non-crate branch of
    /// `ModCrates.LoadSettingsFromFile`) doesn't need to reach into
    /// `ModManifestParser` for what is, in this app, "the settings file
    /// format," not "the manifest file format."
    public static func parse(_ text: String) -> [String: String] {
        ModManifestParser.parseKeyValues(text)
    }

    /// The honest, value-equality analog of CrateModLoader's `HasChanged`-
    /// gated diff-only save (`SaveSettingsToFile(mod, path, fullSettings:
    /// false)`/`SaveSettingsToCrate(mod, path, fullSettings: false)`) —
    /// see this type's own doc comment for exactly how it differs from the
    /// real mutation-flag behavior. Keeps only entries whose value differs
    /// from `defaults`'s value for the same key (a key entirely absent
    /// from `defaults` counts as "differs" — there is no default to match).
    public static func diffFromDefaults(_ settings: [String: String], defaults: [String: String]) -> [String: String] {
        settings.filter { defaults[$0.key] != $0.value }
    }

    /// Same stripping `CrateExporter.sanitizedLine` already applies to
    /// `modcrateinfo.txt` fields, reused here for the same reason: a value
    /// containing its own `=`/newline would desync the first-`=`-only
    /// parse both files share, and there's no escaping convention in the
    /// real format to escape into instead.
    private static func sanitizedLine(_ value: String) -> String {
        value.replacingOccurrences(of: "\n", with: " ").replacingOccurrences(of: "=", with: "-")
    }
}
